name: NestProvider CI/CD
on:
  push:
    branches:
       - master
  pull_request:
    branches: 
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        PACT_BROKER_URL: https://pact-broker.int.k8s.getmobee.com/
        PACT_MOCK_URL: http://localhost:3500 
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install & Tests
        run: 
          npm install
          npm test
      - name: Build Image
        run: docker build -t loneprovider .
      - name: Run Builded Image
        run: docker run -d -p 3000:3000 --name loneprovidercontainer -t loneprovider
      - name: Run Provider test
        run: docker exec loneprovidercontainer PACT_BROKER_URL=$PACT_BROKER_URL PACT_BROKER_USERNAM=${{PACT_BROKER_USERNAME}} PACT_BROKER_PASSWOR=${{PACT_BROKER_PASSWORD}}  npm test 
