name: NestProvider CI/CD
on:
  push:
    branches:
       - master
  pull_request:
    branches: 
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        PACT_BROKER_URL: https://pact-broker.int.k8s.getmobee.com/
        PACT_MOCK_URL: http://localhost:3500 
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: confirm Variables
        run: echo Hello world ${{secrets.pactBrokerUsername}} $PACT_BROKER_URL $GITHUB_SHA
      - name: Install & Tests
        run: 
          npm install
          npm test
      - name: Build Image
        run: docker build -t loneprovider .
      - name: Run Builded Image
        run: |
            docker run -d --env PROVIDER_VERSION=$GITHUB_SHA --env PACT_BROKER_URL=$PACT_BROKER_URL --env PACT_BROKER_USERNAME=${{secrets.PACT_BROKER_USERNAME}} --env PUBLISH_VERIFICATION=true --env PACT_BROKER_PASSWORD=${{secrets.PACT_BROKER_PASSWORD}}  -p 3050:3050 --name loneprovidercontainer -t loneprovider
            docker ps
            docker exec loneprovidercontainer npm run test:pact 